version: '3.1'

services:
  app:
    build:
      args:
        user: root
        uid: 1
      context: ./
      dockerfile: Dockerfile
    container_name: pup-xml-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./application:/var/www